# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0df24efce75a0895df28dfee53b4fe933c3922636403eb20c70b21d0eaaedfcc633cf5729ad77233b972d8070a8af5244786293e6e62d1d72b5ee6a1a8f3bb4c

test:
  secret_key_base: e9f3628f1da9d9e8b9042d4a761553826b329d40da8117a4ae88e59aa53d578291b92207b4caacfb20b837b6799d61a304b9e18e2fa0a20543462b24b91f317e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
